// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// simple_integral
double simple_integral(arma::mat& lmat, arma::vec tseq);
RcppExport SEXP _TDAkit_simple_integral(SEXP lmatSEXP, SEXP tseqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type lmat(lmatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tseq(tseqSEXP);
    rcpp_result_gen = Rcpp::wrap(simple_integral(lmat, tseq));
    return rcpp_result_gen;
END_RCPP
}
// simple_integral_1d
double simple_integral_1d(arma::vec lvec, arma::vec tseq);
RcppExport SEXP _TDAkit_simple_integral_1d(SEXP lvecSEXP, SEXP tseqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lvec(lvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tseq(tseqSEXP);
    rcpp_result_gen = Rcpp::wrap(simple_integral_1d(lvec, tseq));
    return rcpp_result_gen;
END_RCPP
}
// routine_mds
arma::mat routine_mds(arma::mat& dmat, int ndim);
RcppExport SEXP _TDAkit_routine_mds(SEXP dmatSEXP, SEXP ndimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< int >::type ndim(ndimSEXP);
    rcpp_result_gen = Rcpp::wrap(routine_mds(dmat, ndim));
    return rcpp_result_gen;
END_RCPP
}
// compute_slicemean
arma::mat compute_slicemean(arma::cube& dcube);
RcppExport SEXP _TDAkit_compute_slicemean(SEXP dcubeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type dcube(dcubeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_slicemean(dcube));
    return rcpp_result_gen;
END_RCPP
}
// compute_slicewsum
arma::mat compute_slicewsum(arma::cube& dcube, arma::vec weight);
RcppExport SEXP _TDAkit_compute_slicewsum(SEXP dcubeSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type dcube(dcubeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_slicewsum(dcube, weight));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TDAkit_simple_integral", (DL_FUNC) &_TDAkit_simple_integral, 2},
    {"_TDAkit_simple_integral_1d", (DL_FUNC) &_TDAkit_simple_integral_1d, 2},
    {"_TDAkit_routine_mds", (DL_FUNC) &_TDAkit_routine_mds, 2},
    {"_TDAkit_compute_slicemean", (DL_FUNC) &_TDAkit_compute_slicemean, 1},
    {"_TDAkit_compute_slicewsum", (DL_FUNC) &_TDAkit_compute_slicewsum, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TDAkit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
